add bastion tags option
7Factor/terraform-aws-networking pull request #8
Opened 2021-09-01 19:55 UTC by amymaraisane7f

only one variable added - bastion tags which is an array

2021-09-01 19:56 UTC, chris-malloy approved these changes

2021-09-02 13:07 UTC, jduv requested changes

2021-09-02 13:07 UTC, jduv commented on ec2.tf
> +
You don't need the locals here, just set the `for-each` equal to the variable you created. Comment below.

2021-09-02 13:07 UTC, jduv commented on ec2.tf
> +    for_each = local.tags
Replace `local.tags` with `var.bastion_tags` and we're gtg.

2021-09-02 13:07 UTC, jduv commented on variables.tf
> +  default     = []
Yay! Sane default!

2021-09-03 18:18 UTC, chelseagreen submitted a review, later dismissed

2021-09-07 13:03 UTC, jduv commented
This is good. The tags block looks like every other tags block (responding to a comment from @HJain01  on slack.

<img width="607" alt="Screen Shot 2021-09-07 at 09 01 47" src="https://user-images.githubusercontent.com/591405/132349304-258388a4-070d-4ad6-bf44-443cec124f49.png">

Ship it.

2021-09-07 13:03 UTC, jduv approved these changes

2021-09-07 15:24 UTC, chelseagreen approved these changes

2021-09-07 15:26 UTC, chris-malloy commented on ec2.tf
> +  tags          = concat(local.customTags, local.regularTags)
❤️

2021-09-07 15:26 UTC, chris-malloy approved these changes

2021-09-07 15:28 UTC, HJain01 approved these changes

2021-09-07 15:30 UTC, merged